### ISSUE TITLE
Rainglow preventing resource reloading

### ISSUE THREAD

**Issue by Ultimushadow** [ix0rai/rainglow#15]
Hello, I am running a 1.20.1 fabric server with the latest version of Rainglow installed. Whenever I try to /reload, the reload fails, and the log doesn't give me much more than this:

Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310 at io.ix0rai.rainglow.data.RainglowResourceReloader.method_14491(RainglowResourceReloader.java:48) ~[rainglow-1.1.1+mc1.20.1.jar:?]at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[server-intermediary.jar:?]at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]... 35 more

**Comment by ix0rai** [comment]
@Ultimushadow I'll investigate this today, could you provide the full log as well please?

**Comment by ix0rai** [comment]
never mind about the log, this is a simple bug! I'm calling client code from the server once again

**Comment by Ultimushadow** [comment]
Oh haha I just got up, glad it was a simple fix!

**Comment by ix0rai** [comment]
it was, I should have a release out within a couple hours!
