### ISSUE TITLE
Crash on latest 1.20.6 release

### ISSUE THREAD

**Issue by sternschnaube** [ix0rai/rainglow#28]
Encountered an unexpected exception
> [!NOTE]
> This crash has been fixed. This issue remains open because of an unidentified crash in [this comment](https://github.com/ix0rai/rainglow/issues/28#issuecomment-2135625586).
```
java.lang.NoSuchFieldError: Class net.minecraft.class_1477 does not have member field 'io.ix0rai.rainglow.data.RainglowEntity THIS'
	at net.minecraft.class_1477.redirect$gln000$rainglow$spawnParticles(class_1477.java:1092) ~[server-intermediary.jar:?]
	at net.minecraft.class_1477.method_6669(class_1477.java:203) ~[server-intermediary.jar:?]
	at net.minecraft.class_1477.method_5643(class_1477.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.class_5776.method_5643(class_5776.java:83) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_7324(class_1657.java:1298) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_7324(class_3222.java:1705) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244$1.method_34218(class_3244.java:1626) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824$1.method_34213(class_2824.java:174) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_34209(class_2824.java:74) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12062(class_3244.java:1586) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_12251(class_2824.java:61) ~[server-intermediary.jar:?]
	at net.minecraft.class_2824.method_11054(class_2824.java:15) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:25) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.wrapOperation$dek000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:552) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:841) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:168) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:817) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:792) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by ix0rai** [comment]
this one I don't understand. I'll look into it tonight

**Comment by ix0rai** [comment]
@sternschnaube are you able to consistently reproduce the second crash you shared? I'm unable to reproduce or find a cause

**Comment by ix0rai** [comment]
I'll release a new version fixing the other crash, so that you can more easily test.

**Comment by sternschnaube** [comment]
I will test more, thanks!

**Comment by ix0rai** [comment]
uploaded as https://modrinth.com/mod/rainglow/version/rzOiVsV0

**Comment by sternschnaube** [comment]
I think it can be closed for now 😄
